name: registry-workshop
version: 0.1.0.0
synopsis: build your own registry library

description: this project contains a step by step tutorial on how to build a library like registry
             so that it feels less magic.

extra-source-files: README.md

category: Control

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry-workshop

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -optP-Wno-nonportable-include-path

default-extensions:
 - BangPatterns
 - DefaultSignatures
 - EmptyCase
 - ExistentialQuantification
 - FlexibleContexts
 - FlexibleInstances
 - FunctionalDependencies
 - GADTs
 - GeneralizedNewtypeDeriving
 - InstanceSigs
 - KindSignatures
 - LambdaCase
 - MultiParamTypeClasses
 - MultiWayIf
 - NamedFieldPuns
 - NoImplicitPrelude
 - OverloadedStrings
 - PatternSynonyms
 - Rank2Types
 - RankNTypes
 - ScopedTypeVariables
 - StandaloneDeriving
 - StrictData
 - TupleSections
 - TypeApplications
 - TypeFamilies
 - TypeFamilyDependencies
 - TypeOperators

dependencies:
  - base                  >= 4.14 && < 5
  - containers            >= 0.5  && < 0.7
  - exceptions            >= 0.8  && < 0.11
  - hashable              >= 1.2  && < 1.5
  - mtl                   >= 2.0  && < 3
  - mmorph                >= 1.0  && < 2
  - protolude             >= 0.2  && < 0.4
  - resourcet             >= 1.1  && < 1.3
  - semigroupoids         >= 5.0  && < 5.4
  - semigroups            >= 0.15 && < 0.30
  - template-haskell      >= 2.13 && < 3.0
  - text                  >= 1.1  && < 2
  - transformers-base     >= 0.4  && < 0.5

library:
  source-dirs: src

  ghc-options:
    -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry-workshop
      - async            < 2.3
      - bytestring       < 0.12
      - directory        < 1.4
      - hedgehog         >= 1.0 && < 3.0
      - generic-lens     >= 1.0 && < 3.0
      - io-memoize       < 1.2
      - MonadRandom      < 0.6
      - multimap         < 1.3
      - semigroups       < 0.30
      - random           < 2.0
      - tasty            < 1.5
      - tasty-discover   < 4.3
      - tasty-hedgehog   >= 1.2 && < 2.0
      - tasty-th         < 0.2
      - text             < 2
      - universum        < 2

    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -fno-warn-incomplete-uni-patterns
      -optP-Wno-nonportable-include-path
